name: Flask App CI
on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main ]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: Create and activate virtual environment
      run: |
        python -m venv venv
        source venv/bin/activate
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        pip install pytest flake8
    - name: Lint with flake8
      run: |
        source venv/bin/activate # Ensure venv is active
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics --exclude=venv
    - name: Test with pytest
      run: |
        source venv/bin/activate
        pytest test_flask_app.py
